name: Daily builds of monaco-typescript and monaco of TypeScript

on: push
  # schedule:
  # - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - run: "npm install -g json"

    - name: Setup Monaco TypeScript
      run: |
        git clone https://github.com/microsoft/monaco-typescript.git
        cd monaco-typescript
        npm i

        # set up the monaco to be based on the nightly version
        npm run run-nightly
        npm run prepublishOnly

        json -I -f package.json -e "this.name='@orta/monaco-typescript'"
        json -I -f package.json -e "this.publishConfig={'access': 'public'}"
        
        MONACO_TS_VERSION=$(json -f package.json version)
        cd ..

    - name: Deploy Monaco TypeScript
      uses: primer/publish@master
      with:
        args: "--dir monaco-typescript"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Monaco Editor
      run: |
        git clone https://github.com/microsoft/monaco-editor.git
        cd monaco-editor

        json -I -f package.json -e "this.name='@orta/monaco-editor'" 
        yarn add monaco-typescript@npm:@orta/monaco-typescript@$MONACO_TS_VERSION

        # Create a release build, this makes a new sub-folder called release with the module
        gulp release

    - name: Deploy Monaco Editor
      uses: primer/publish@master
      with:
        args: "--dir monaco-editor/release"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
