name: Build a version of TypeScript on request
on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    # Lets us use one-liner JSON manipulations on package.jsons
    - run: "npm install -g json"

    - name: Setup Monaco TypeScript
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: | 
        ENCODED_TS_VERSION=$(json f $GITHUB_EVENT_PATH action )
        DECODED_TS_VERSION=$(php -R 'echo urldecode($ENCODED_TS_VERSION)."\n";')
        echo "Publishing Monaco based on $DECODED_TS_VERSION"
        publish-monaco-ts.sh $DECODED_TS_VERSION


    - name: Setup Monaco Editor
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cat $GITHUB_EVENT_PATH
        # publish-monaco-editor.sh 


