name: Tagged Build

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"

      # Lets us use one-liner JSON manipulations on package.jsons
      - run: "npm install -g json"

      # For Azure uploads
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Setup Monaco TypeScript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          FULL_TAG_REF: ${{ github.ref }}
        run: "node ./publish-monaco-ts.js $(echo $FULL_TAG_REF | cut -d/ -f3) "

      - name: Setup Monaco Editor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          FULL_TAG_REF: ${{ github.ref }}
        run: "node ./publish-monaco-editor.js $(echo $FULL_TAG_REF | cut -d/ -f3)"

      - name: Upload to Azure
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: node ./upload-assets-to-blob-storage.js
