name: Tagged Build

on:
   push:
     tags:
     - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    # Lets us use one-liner JSON manipulations on package.jsons
    - run: "npm install -g json"

    - name: Setup Monaco TypeScript
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        FULL_TAG_REF: ${{ github.ref }}
      run: node ./publish-monaco-ts.js $(echo $FULL_TAG_REF | cut -d/ -f3)

    - name: Setup Monaco Editor
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: node ./publish-monaco-editor.js $(echo $FULL_TAG_REF | cut -d/ -f3)


